name: Chatterbox
version: ${project.build.version}
main: com.tealcube.minecraft.bukkit.chatterbox.ChatterboxPlugin
depend: [Facecore, Vault]

permissions:
  chatterbox.commands.list:
    default: true
  chatterbox.commands.use:
    default: true
  chatterbox.commands.ignore:
    default: true

commands:
  title:
    aliases: []
  whisper:
    aliases: [w, tell, pm, message, msg]
  ignore:
    aliases: [ign]
  reply:
    aliases: [r, rep]
  continue:
    aliases: [c, cont, con]