name: Chatterbox
version: ${project.version}
main: com.tealcube.minecraft.bukkit.chatterbox.ChatterboxPlugin
depend: [Facecore, Vault]

permissions:
  chatterbox.commands.list:
    default: true
  chatterbox.commands.use:
    default: true
  chatterbox.commands.ignore:
    default: true

commands:
  title:
    aliases: []
  ignore:
    aliases: [ign]